### ISSUE TITLE
Over-reaching permissions

### ISSUE THREAD

**Issue by dashbad** [wltrsjames/Ultrawide-Video#7]
Is it really necessary for this extension to be able to: "Read and Change all your data on all the websites you visit"?

Why is it not limited to certain sites?

**Comment by wltrsjames** [comment]
Because the intention was to get it to work with more players. I can't physically check them all. I wrote some code that will in theory work with most non webm and iframe players,

**Comment by dashbad** [comment]
I see. When you initially launched it was it only for Youtube? I'm not questioning your motives, and I like the functionality it provides, but the permissions it requires are a little scary.

**Comment by wltrsjames** [comment]
Believe it or not, even when this extension was only for youtube, the permissions to access the page were and have always been the same, because I was a noob and I didn't know what was okay (it was 2 years ago). I merged a commit that added chrome alerts to notify updates. This change is what triggered the re-accept of the terms.
